# -*- coding: utf-8 -*-
"""kod1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GBUZyLToLPhlGaE2JEE-O1z2XCdKgK8P
"""

prime_second= ()
for i in range(500, 1000):
  nums = filter(lambda x: x== i or x % i, nums )
  print (i)

